# Generated by Django 3.2.16 on 2024-05-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('position', models.TextField()),
                ('gpa', models.FloatField()),
            ],
        ),
    ]
