# Generated by Django 3.2.16 on 2024-05-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='position',
            field=models.TextField(null=True),
        ),
    ]
